In [1]:
import numpy as np
# 1D Array
a = np.array([0, 1, 2, 3, 4])
b = np.array((0, 1, 2, 3, 4))
c = np.arange(5)
d = np.linspace(0, 2*np.pi, 5)

In [31]:
y = np.linspace(0, 2, 10)
print(y)

[0.         0.22222222 0.44444444 0.66666667 0.88888889 1.11111111
 1.33333333 1.55555556 1.77777778 2.        ]


In [18]:
print(a.ndim) 
print(b) 
print(c) 
print(d) 
print(a[3]) 

2
[0 1 2 3 4]
[0 1 2 3 4]
[0.         1.57079633 3.14159265 4.71238898 6.28318531]
[26 27 28 29 30]


In [14]:
z = np.array([[11, 12, 13, 14, 15],
              [16, 17, 18, 19, 20],
              [21, 22, 23, 24, 25],
              [26, 27, 28 ,29, 30],
              [31, 32, 33, 34, 35]])

print(z[2,4]) 

25


In [10]:
print(z[2,:])

[21 22 23 24 25]


In [11]:
print(z[:,4])

[15 20 25 30 35]


In [13]:
print(z[0, 1:4]) 
print(z[1:4, 0]) 
print(z[:, 1])

[12 13 14]
[16 21 26]
[12 17 22 27 32]


In [17]:
# Array properties
z = np.array([[11, 12, 13, 14, 15],
              [16, 17, 18, 19, 20],
              [21, 22, 23, 24, 25],
              [26, 27, 28 ,29, 30],
              [31, 32, 33, 34, 35]])

print(type(z)) 
print(z.dtype) 
print(z.size) #number of Elements 
print(z.shape) # rows x columns
print(z.ndim) # number of dimensions

<class 'numpy.ndarray'>
int32
25
(5, 5)
2


In [26]:
# Basic Operators
a = np.arange(25)
a = a.reshape((5, 5))

b = np.array([10, 62, 1, 14, 2, 56, 79, 2, 1, 45,
              4, 92, 5, 55, 63, 43, 35, 6, 53, 24,
              56, 3, 56, 44, 78])
b = b.reshape((5,5))
print('Reshaped Matrix')
print(b)
print('Addition')
print(a + b)
print('Subtraction')
print(a - b)
print('Multiplication')
print(a * b)
print('Division')
print(a / b)
print('Power')
print(a ** 2)
print('Less than')
print(a < b)
print('Greater than')
print(a > b)
print('Dot Product')
print(a.dot(b))

Reshaped Matrix
[[10 62  1 14  2]
 [56 79  2  1 45]
 [ 4 92  5 55 63]
 [43 35  6 53 24]
 [56  3 56 44 78]]
Addition
[[ 10  63   3  17   6]
 [ 61  85   9   9  54]
 [ 14 103  17  68  77]
 [ 58  51  23  71  43]
 [ 76  24  78  67 102]]
Subtraction
[[-10 -61   1 -11   2]
 [-51 -73   5   7 -36]
 [  6 -81   7 -42 -49]
 [-28 -19  11 -35  -5]
 [-36  18 -34 -21 -54]]
Multiplication
[[   0   62    2   42    8]
 [ 280  474   14    8  405]
 [  40 1012   60  715  882]
 [ 645  560  102  954  456]
 [1120   63 1232 1012 1872]]
Division
[[0.         0.01612903 2.         0.21428571 2.        ]
 [0.08928571 0.07594937 3.5        8.         0.2       ]
 [2.5        0.11956522 2.4        0.23636364 0.22222222]
 [0.34883721 0.45714286 2.83333333 0.33962264 0.79166667]
 [0.35714286 7.         0.39285714 0.52272727 0.30769231]]
Power
[[  0   1   4   9  16]
 [ 25  36  49  64  81]
 [100 121 144 169 196]
 [225 256 289 324 361]
 [400 441 484 529 576]]
Less than
[[ True  True False  True False]
 [ True  True False

In [25]:
# dot, sum, min, max, cumsum
a = np.arange(10)
print(a)
print(a.sum()) 
print(a.min()) 
print(a.max()) 
print(a.cumsum()) # Elementwise addition

[0 1 2 3 4 5 6 7 8 9]
45
0
9
[ 0  1  3  6 10 15 21 28 36 45]


In [24]:
x = np.zeros((2,2))   # Create an array of all zeros
print(x)              # Prints "[[ 0.  0.]
                      #          [ 0.  0.]]"


[[0. 0.]
 [0. 0.]]


In [26]:
w = np.ones((1,2))   
print(w)

[[1. 1.]]


In [22]:
V = np.full((2,2), 9)  
print(V)  

[[9 9]
 [9 9]]


In [23]:
d = np.eye(2)         # identity matrix
print(d) 

[[1. 0.]
 [0. 1.]]


In [21]:
e = np.random.random((2,2))  # Create an array filled with random values
print(e)                     
           

[[0.79172504 0.52889492]
 [0.56804456 0.92559664]]


In [30]:
I = np.ones((5,5))
print(I)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [31]:
I[None] = 0 
print(I)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [32]:
j = np.array([[1,2], [3, 2], [5, 1]])

In [34]:
idx = (a > 2) 
print(idx)

[False False False  True  True  True  True  True  True  True]


In [35]:
print(a[a > 2])

[3 4 5 6 7 8 9]


In [36]:
x = np.array([[1,2], [13, 2], [12, 1]])
### START CODE HERE ### (≈ 1 line of code)
y = None                
### END CODE HERE ###

In [37]:
print(y)

None


In [27]:
x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)

In [28]:
print(np.add(x, y))

[[ 6.  8.]
 [10. 12.]]


In [29]:
print(np.sqrt(x))

[[1.         1.41421356]
 [1.73205081 2.        ]]


In [30]:
x = np.exp(x) 
print(x)

[[ 2.71828183  7.3890561 ]
 [20.08553692 54.59815003]]


In [42]:
x = np.array([[1,2],[3,4]])  # What does this array look like?

print(np.sum(x))  # Compute sum of all elements; prints "10"
print(np.sum(x, axis=0))  # Compute sum of each column; prints "[4 6]"
print(np.sum(x, axis=1))

10
[4 6]
[3 7]


In [53]:
m = np.array([[1,2],[3,4]])
print(m)

[[1 2]
 [3 4]]


In [52]:
n = np.array([[1,2],[3,4]])
print(n)

[[1 2]
 [3 4]]


In [54]:
g=np.matmul(m,n)
print(g)

[[ 7 10]
 [15 22]]


In [19]:
import numpy as np
np.random.seed(0) 
perm = np.random.permutation(10)
print(perm)

[2 8 4 9 1 6 7 3 0 5]


In [3]:
print(np.random.seed(0) )

None


In [7]:
 print(len(np.random.rand(100000)))

100000


In [18]:
np.random.rand(4)

array([0.14335329, 0.94466892, 0.52184832, 0.41466194])